name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8   

    - name: Change directory to android/
      run: cd Android_BDD_UI/

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Run tests
      run: ./gradlew testDebug

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/test-results
