name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8   

    - name: Grant execute permission for gradlew
      run: chmod +x Android_BDD_UI/gradlew

    - name: Build with Gradle
      run: Android_BDD_UI/gradlew assembleDebug

    - name: Run tests
      run: Android_BDD_UI/gradlew testDebug

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/test-results
